package recipe

import (
	"fmt"
	"io"

	"gopkg.in/yaml.v3"

	"github.com/castai/kimchi/internal/config"
)

const fileHeader = "# Generated by kimchi recipe export\n# https://github.com/castai/kimchi\n\n"

// WriteYAML marshals r to YAML and writes it to outputPath.
// A comment header is prepended to the file. Intermediate directories are
// created as needed. The write is atomic (temp file + rename).
func WriteYAML(outputPath string, r *Recipe) error {
	data, err := yaml.Marshal(r)
	if err != nil {
		return fmt.Errorf("marshal recipe: %w", err)
	}

	out := append([]byte(fileHeader), data...)

	if err := config.WriteFile(outputPath, out); err != nil {
		return fmt.Errorf("write recipe file: %w", err)
	}

	return nil
}

// WriteYAMLTo marshals r to YAML and writes it to w (e.g. os.Stdout for --dry-run).
func WriteYAMLTo(w io.Writer, r *Recipe) error {
	data, err := yaml.Marshal(r)
	if err != nil {
		return fmt.Errorf("marshal recipe: %w", err)
	}
	_, err = fmt.Fprint(w, fileHeader)
	if err != nil {
		return err
	}
	_, err = w.Write(data)
	return err
}
