version: 2

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/castai/kimchi/internal/version.Version={{.Version}}
      - -X github.com/castai/kimchi/internal/telemetry.PostHogAPIKey={{.Env.POSTHOG_API_KEY}}
    binary: kimchi

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

release:
  github:
    owner: castai
    name: kimchi
  extra_files:
    - glob: scripts/install.sh
      name_template: install.sh

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
